<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>MW4RemasteredInstaller</AssemblyName>
    <RootNamespace>MW4Remastered.Installer</RootNamespace>
    <ApplicationIcon>..\..\assets\branding\MW4-Remastered.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MW4Remastered.Core\MW4Remastered.Core.csproj" />
  </ItemGroup>
</Project>
